### PR TITLE
Update `npmName.many` to throw an `AggregateError` when warranted

### PR DESCRIPTION
**Pull request by baile320**
Fixes https://github.com/sindresorhus/npm-name/issues/29

### CODE REVIEW

**Comment by sindresorhus** [comment]
`p-map` now has a `stopOnError` option you can use.

**Comment by sindresorhus** [comment]
@baile320 Interested in finishing this? 🙏

**Comment by baile320** [comment]
@sindresorhus sure, i switched to using that optional setting on p-map, let me know if you have any comments.

**Comment by sindresorhus** [comment]
I think something got messed up during your merge: https://github.com/sindresorhus/npm-name/pull/30/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R3

**Pull request closed without merging**
